blank_issues_enabled: true
contact_links:
  - name: Questions and discussions
    url: https://github.com/tanmaytyagii/amazon-clone-nextjs/discussions
    about: Ask questions and discuss ideas with the community.
